### ISSUE TITLE
Sprinklers are not placed

### ISSUE THREAD

**Issue by M1dnight-ofcl** [NatroTeam/NatroMacro#144] opened 2024-01-13 01:53 UTC
### Have you searched the existing bug reports?

No

### What happened?

Even though i set up sprinklers properly, they still don't work.

### Steps to reproduce

Just try to set them up with anything but supreme sprinklers.

### What would you expect to happen?

I expected it to place them

### Natro Macro version

0.9.9

### What is your Discord username?

m1dnightdev

**Comment by zspz** [comment] 2024-01-15 12:32
I believe this is a duplicate of #125, maybe just jump power and not bear morph.
Please post details of your issue there!

**Closed by zspz** 2024-01-15 12:32 UTC
Labels: bug, needs triage
