### ISSUE TITLE
Macro pauses itself after Roblox crash

### ISSUE THREAD

**Issue by NimbusRod** [NatroTeam/NatroMacro#58] opened 2023-12-04 07:19 UTC
### Have you searched the existing bug reports?

Yes

### What happened?

I left my macro to run overnight, everything was working fine, but then in the middle of the night roblox crashed, and macro just paused itself 1 minute later.
![image](https://github.com/NatroTeam/NatroMacro/assets/111235082/385a62f7-00aa-43a6-b54f-c86d9dd2d6cc)
macro didnt even try to reconnect or something

### Steps to reproduce

1.run the macro
2.wait until roblox crashes
3.it should pause itself

### What would you expect to happen?

Macro would probably pause itself and stop working, however im not sure it will always work

### Natro Macro version

0.9.7

### What is your Discord username?

golden_sock

**Comment by zspz** [comment] 2023-12-05 01:15
This is caused by the macro activating Pause on the Natro Macro GUI when Roblox crashes and the GUI is the window directly underneath. You can fix it for now by minimising the GUI before pressing F1 to start the macro. It will be no longer occur from the next version onwards.
https://discord.com/channels/1012610056921038868/1177132401894375444

**Comment by zspz** [comment] 2024-01-15 12:40
Fixed in v0.9.9

**Closed by zspz** 2024-01-15 12:40 UTC
Labels: bug
