### ISSUE TITLE
Mondo is not detecting Kill

### ISSUE THREAD

**Issue by xltzStephx** [NatroTeam/NatroMacro#56] opened 2023-12-03 17:20 UTC
### Have you searched the existing bug reports?

Yes

### What happened?

In the past 10+ days i found out few bugs in natro 0.97
* Wrong night detection 9/10 times when you go to kill mondo
* Mondo kill not detected, so loot is not picked up. It will just wait until 15th min of the hour and then reset.

### Steps to reproduce

1.eneble natro for mondo kill/loot
2.enable vic kill for all fields
3.enable polar and riley tasks. That is what i have enable on my version of natro

### What would you expect to happen?

I was using natro 0.91 for long time, and that version never missfire on night detection or mondo kill. Changes on natro 0.97 for mondo location made the errors, so my suggestion is to return previous location on mondo stay and kill, that will solve both the kill detection of mondo and also wrong night detection

### Natro Macro version

0.97

### What is your Discord username?

stephman.

**Comment by zspz** [comment] 2023-12-05 01:01
The Mondo changes you are referring to were made in v0.9.5, and I agree that it is not in a very stable state at the moment.
Night detection is done by a constant background image search, so there is probably no relation with that and Mondo.
So, I have changed this issue to focus on the Mondo problem.

**Comment by xltzStephx** [comment] 2023-12-26 15:39
Hi All,
Thx for the update, however i noticed in the latest version of natro the
same issue with the mondo. The kill detection is not register and if natro
reset for night while killing mondo, after vic bee is killed , it will
return on the MT for the mondo kill, but bcs mondo died earlier- while
chasing the vic, the acc will just sit there until 15th min. For suggestion
to possible resolution what i have done in the Jitbit macro is to multiple
check for mondo kill for fraction of the mondo picture in the whole screen-
see attached pic.
That solve mine issue and mondo kill was always registered:
[image: image.png]
I hope in the next release you will guys fix this major mondo issue, bcs
for players who depend on mondo kill and their loot, currently with natro,
we have 90% miss loot

Regards,

Steph

**Comment by zspz** [comment] 2024-01-29 16:44
Hi @xltzStephx,
Apologies for the late response.
I've been running Mondo on Kill for the past few days and the only issue I've experienced is slow kill detection (macro waits too long after the kill to begin looting).
I've also had Vicious Bee on but haven't had any night misdetections related to Mondo.
To clarify, the issues caused by v0.9.5's changes to Mondo have not yet been fully addressed, but it is working to a reasonable extent for me.
Improvements are definitely needed though!

**Comment by zspz** [comment] 2024-01-30 22:46
Thanks for the report, all known Mondo issues will be fixed in the next version:
- removed unnecessary alignment after cannon use
- fixed fully grown planter affecting Mondo detection (causing it to wait for 15 mins)
- re-added wrongly removed detection of Mondo death message, fixing delayed looting
- reworked looting to stretch over the whole field instead of only half

**Closed by zspz** 2024-01-30 22:46 UTC
Labels: bug
