### ISSUE TITLE
Critical error: function recursion limit exceeded

### ISSUE THREAD

**Issue by 1cyM1nt000** [NatroTeam/NatroMacro#191] opened 2024-01-17 13:25 UTC
### Have you searched the existing bug reports?

I searched on GitHub issues section and there's likely to be no existing issue.

### What happened?

![Screenshot 2024-01-17 200757](https://github.com/NatroTeam/NatroMacro/assets/94796529/6b55ab92-7bbb-4d6c-8ddd-3d0de08eaf6f)
I turned on macro and leave my pc for nearly 6 hours. When I came back, I saw this pop-up and the macro broke. I couldn't ask about the problem in Discord because somehow I got both "member" and "incomplete tutorial" role, and when I did the tutorial, it just revoke all role and gave me "unverified" role.

### Steps to reproduce

I think the main cause is leaving the macro running for too long. Maybe I can reproduce this by leaving the pc for another 6 hours.

### What would you expect to happen?

The macro running perfectly.

### Natro Macro version

0.9.9.1

### What is your Discord username?

1cyM1nt000 (roblox account: bzz071217)

**Comment by zspz** [comment] 2024-01-17 22:11
Is this a recurring issue? It doesn't seem to be an issue of Natro Macro since the recursion is on the WinWait line.
Are you running the macro with START.bat?

**Comment by 1cyM1nt000** [comment] 2024-01-18 11:22
> Is this a recurring issue? It doesn't seem to be an issue of Natro Macro since the recursion is on the WinWait line. Are you running the macro with START.bat?

Yes, I am. I don't really know other ways to start it.

**Comment by zspz** [comment] 2024-01-18 11:35
That's fine, I only asked because you may be running a different version of AHK if you didn't run with START.bat.
Has this error appeared more than once?

**Comment by 1cyM1nt000** [comment] 2024-01-18 15:43
No. I've tried to macro for a long period of time before, but it usually ends up with infinite "BSS not found".
One more thing I noticed is that before it crashed, the program had continuously tried to start "Vicious Bee Cycle", and then just kept detecting night, but didn't do anything else.
![image](https://github.com/NatroTeam/NatroMacro/assets/94796529/beac9c34-b052-4268-81b2-ce7ee2327e9d)
Hope this helps!

**Comment by zspz** [comment] 2024-01-18 20:55
That's expected, since only natro_macro.ahk crashed but the other processes are still running (including background.ahk which detects night).
Repeated "BSS not found" sounds like your reconnect is not set up correctly, try to test it and ask in our Discord server and check the guides there if there's an issue.

**Comment by zspz** [comment] 2024-01-18 20:56
I'm going to close this regarding the original Critical Error, since I don't believe it was caused by the macro's code, and it seems to have been a one-time thing.

**Closed by zspz** 2024-01-18 20:56 UTC
Labels: bug, needs triage
