### ISSUE TITLE
High hp bugs wont die fast enough for bees to kill them, usually due to bees put in rest from all the player resets

### ISSUE THREAD

**Issue by Rysleo2** [NatroTeam/NatroMacro#346] opened 2024-02-25 08:57 UTC
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

some way for the code to check if the player is loosing hp, or activating its ability to keep the player from resetting, or add an option that the player stays in the field for x seconds before resetting.

### How will this improve Natro Macro?

Faster and more efficient bug runs

**Comment by zspz** [comment] 2024-02-27 13:28
This seems like a duplicate of #303.
Also make sure to decrease your Hive Bees number or increase the wait delay after convert in Settings tab.

**Closed by zspz** 2024-02-27 13:28 UTC
Labels: suggestion, needs triage
