### ISSUE TITLE
Add macro options for hive hub field

### ISSUE THREAD

**Issue by BenDoverEatYourSocks** [NatroTeam/NatroMacro#620] opened 2024-08-05 18:38 UTC
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add an option to macro in the Hive Hub field.

### How will this improve Natro Macro?

The reason I want this is because you can farm sticker sprouts and getting tool stickers are easier here.

### What is your Discord username?

qweqeqweqewqwe

**Comment by peacocksir** [comment] 2024-08-08 15:14
This is already planned for the next release. Duplicate of #185

**Closed by peacocksir** 2024-08-08 15:14 UTC
Labels: suggestion, needs triage
